Capstone-Projects-2025-Spring/project-acc-hungry-hippos

README.md

Modified the existing program abstract such that it explains what is to be done in this capstone project.

Updated Program Abstract in README

---

README.md

Changed Project Name to reflect the name of our project.

Updated Project Name

---

index.html
src/AacInterface.jsx

Added a recognition of what fruit was selected from the AAC device to be reflected onto the game itself

AAC device to game fruit recognition

---

documentation/docs/requirements/use-case-descriptions.md

Updated use-case-descriptions.md

HHP-45: Req doc revision - Use case description

---

documentation/docs/system-architecture/sequence-diagrams.md

Use case 2

---

documentation/docs/system-architecture/class-diagrams.md

added frontend class diagram and relationship description

---

Hungry-Hippo-Game/src/PhaserGame.tsx
Hungry-Hippo-Game/src/game/scenes/Game.ts
documentation/docs/api-specification/Frontend.md

API Docs for Game.ts and PhaserGame.tsx

Api doc for game and phaser game

---

documentation/docs/testing/unit-testing.md

Added chosen testing library and test unit-testing procedures for methods in Game.ts

Added to unit-testing doc

---

Hungry-Hippo-Game/sessionAPI.js
Hungry-Hippo-Game/src/aac/AacInterface.tsx
Hungry-Hippo-Game/src/contexts/WebSocketContext.tsx
Hungry-Hippo-Game/src/main.tsx
Hungry-Hippo-Game/src/pages/GamePage/GamePage.tsx
Hungry-Hippo-Game/src/pages/LandingPage/LandingPage.tsx
Hungry-Hippo-Game/src/pages/PresenterPage/Presenter.tsx
Hungry-Hippo-Game/src/pages/RoleSelection/RoleSelect.tsx

Implementations:
- WebSocketProvider to manage a single app-wide WebSocket connection
- useWebSocket custom hook for the provider
Changes:
- Converted 3 pages (GamePage, LandingPage, Presenter) and AacInterface to WebSocket
- Fully converted sessionAPI from REST API to WebSockets for multiplayer real-time sync
Removed LIFO stack for now until it's managed by the server

Hhp 2 players joined the session

---

Hungry-Hippo-Game/src/game/scenes/Game.ts
Hungry-Hippo-Game/src/pages/GamePage/GamePage.tsx

Added:
- Point and penalty logic for when hippo does not eat target food
- Console logging
Removed:
- Old collision handler method handleFoodCollision

Added point penalty when hippo eats non-target fruit

---

Hungry-Hippo-Game/sessionAPI.js
Hungry-Hippo-Game/src/game/scenes/Game.ts
Hungry-Hippo-Game/src/pages/GamePage/GamePage.tsx

Changed:
- Food now launches from the center in random directions instead of from the top
Implemented:
- Food launches in sync between users
Added:
- Exact direction console logging

Hhp 54 fruit spawns from center

---

Hungry-Hippo-Game/sessionAPI.js
Hungry-Hippo-Game/src/config/gameModes.ts
Hungry-Hippo-Game/src/contexts/WebSocketContext.tsx
Hungry-Hippo-Game/src/game/scenes/Game.ts
Hungry-Hippo-Game/src/pages/PhaserPage/PhaserPage.tsx
Hungry-Hippo-Game/src/pages/PresenterPage/Presenter.module.css
Hungry-Hippo-Game/src/pages/PresenterPage/Presenter.tsx

Summary:
- UI for game mode (easy, medium , hard)
- Logic for different modes connected to websocket
- Currently only set up to have 
Easy: {
fruitSpeed: 100,
allowPenalty: false,
},
Medium: {
fruitSpeed: 150,
allowPenalty: true,
},
Hard: {
fruitSpeed: 300,
allowPenalty: true,
fruitSpeed is how fast fruits are moving, allowPenalty is if negative point scored for wrong fruit
Screenshot of payload

Hhp 75 game mode screen5

---

Hungry-Hippo-Game/sessionAPI.js
Hungry-Hippo-Game/src/contexts/WebSocketContext.tsx
Hungry-Hippo-Game/src/game/scenes/Game.ts
Hungry-Hippo-Game/src/pages/PhaserPage/PhaserPage.tsx
Hungry-Hippo-Game/src/router.tsx

movement synced between players

 movement synced  between all players

---

Hungry-Hippo-Game/sessionAPI.js
Hungry-Hippo-Game/src/game/scenes/Game.ts
Hungry-Hippo-Game/src/pages/PhaserPage/PhaserPage.tsx

Implemented:
- Food launches to be in sync in all hippo players in a session screens

Synced food launches across hippo players screens

---

Hungry-Hippo-Game/sessionAPI.js
Hungry-Hippo-Game/src/game/scenes/Game.ts

Implemented:
- Initial broadcast to show hippo players with score of 0
Changed:
- Fruit collision logic to prevent race conditions (attempt 2)
Fixed:
- Leaderboard scoring
- Interpolation bug

Hhp 69 slow down food remove bounce

---

Hungry-Hippo-Game/sessionAPI.js
Hungry-Hippo-Game/src/pages/PhaserPage/PhaserPage.tsx

Changed:
- Food launches one by one slowly now so
- The aac selected food in the set does not always launch first for every hippo player (randomized)

Changed to slower gameplay and unique sets for hippos

---

Hungry-Hippo-Game/sessionAPI.js
Hungry-Hippo-Game/src/game/scenes/Game.ts
Hungry-Hippo-Game/src/pages/PhaserPage/PhaserPage.module.css
Hungry-Hippo-Game/src/pages/PhaserPage/PhaserPage.tsx

Implemented:
- Food to continuously launch until timer ends
- Initial food launched to be set as target food until AAC user selects a food
Changed:
- Food launched is now the same across hippo users
Fixed:
- Attempted to fix food not launching in correct directions bug
Added:
- Some logging to help with debugging
- Styling to timer

Hhp 92 food spawning direction

---

Hungry-Hippo-Game/sessionAPI.js

Added:
- Target food weight to make the target food selected appear more often in the stream

Added target food weight

---

Hungry-Hippo-Game/src/pages/PhaserPage/PhaserPage.module.css

Added:
- Scaling for side bar for various devices
Changed:
- Organized PhaserPage.module.css a bit

Scaled sidebar for various devices

---

documentation/docs/api-specification/Frontend.md
documentation/docs/requirements/system-block-diagram.md
documentation/docs/system-architecture/class-diagrams.md
documentation/docs/system-architecture/component-descriptions.md

Changed:
- Frontend class diagram
- Some formatting of the docs to fix table of contents

Updated frontend class diagram

---

Hungry-Hippo-Game/sessionAPI.js

Completely updated db
